"use client"

import { useState, useCallback, useEffect } from "react"
import { Download, Copy, Check, Code, Globe, RotateCcw, Smartphone } from "lucide-react"
import { toast } from "sonner"
import { FileDropzone } from "@/components/file-dropzone"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { downloadBlob, formatBytes } from "@/lib/download"
import { loadImage } from "@/lib/image"

interface IconSpec {
  size: number
  label: string
  name: string
  url: string | null
  blob: Blob | null
}

const ICON_SIZES = [
  { size: 16, label: "16×16 (Tab Favicon)", name: "favicon-16x16.png" },
  { size: 32, label: "32×32 (Retina Favicon)", name: "favicon-32x32.png" },
  { size: 48, label: "48×48 (Windows Shortcut)", name: "favicon-48x48.png" },
  { size: 180, label: "180×180 (Apple Touch)", name: "apple-touch-icon.png" },
  { size: 512, label: "512×512 (PWA App Icon)", name: "android-chrome-512x512.png" },
]

export default function FaviconGenerator() {
  const [file, setFile] = useState<File | null>(null)
  const [previewUrl, setPreviewUrl] = useState<string | null>(null)
  const [icons, setIcons] = useState<IconSpec[]>([])
  const [copiedHtml, setCopiedHtml] = useState(false)

  function reset() {
    if (previewUrl) URL.revokeObjectURL(previewUrl)
    icons.forEach((i) => i.url && URL.revokeObjectURL(i.url))
    setFile(null)
    setPreviewUrl(null)
    setIcons([])
  }

  function onFiles(files: File[]) {
    const f = files[0]
    if (!f.type.startsWith("image/")) {
      toast.error("Please upload an image file.")
      return
    }
    reset()
    setFile(f)
    setPreviewUrl(URL.createObjectURL(f))
  }

  const generateFavicons = useCallback(async () => {
    if (!previewUrl) return
    try {
      const img = await loadImage(previewUrl)
      const results: IconSpec[] = []

      for (const spec of ICON_SIZES) {
        const canvas = document.createElement("canvas")
        canvas.width = spec.size
        canvas.height = spec.size
        const ctx = canvas.getContext("2d")
        if (!ctx) continue

        ctx.clearRect(0, 0, spec.size, spec.size)
        ctx.drawImage(img, 0, 0, spec.size, spec.size)

        const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png"))
        if (blob) {
          results.push({
            ...spec,
            blob,
            url: URL.createObjectURL(blob),
          })
        }
      }
      setIcons(results)
    } catch {
      toast.error("Error generating icon sizes.")
    }
  }, [previewUrl])

  useEffect(() => {
    generateFavicons()
  }, [generateFavicons])

  const htmlHeadMarkup = `<!-- Favicons generated by Toolbox -->
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">`

  function copyHtmlMarkup() {
    navigator.clipboard.writeText(htmlHeadMarkup)
    setCopiedHtml(true)
    toast.success("HTML <head> tags copied to clipboard!")
    setTimeout(() => setCopiedHtml(false), 2000)
  }

  if (!file) {
    return (
      <FileDropzone
        accept="image/*"
        onFiles={onFiles}
        label="Drop your logo to generate a full Favicon package"
        hint="Generates 16x16, 32x32, 48x48, 180x180, 512x512 icons 100% locally"
      />
    )
  }

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-border bg-card p-5">
        <div>
          <h3 className="font-semibold text-sm">{file.name}</h3>
          <p className="text-xs text-muted-foreground">{formatBytes(file.size)} • 5 Multi-resolution favicon sizes ready</p>
        </div>
        <Button variant="ghost" size="sm" onClick={reset}>
          <RotateCcw className="size-4 mr-1.5" /> Start Over
        </Button>
      </div>

      {/* Main Grid: Generated Icons & Context Previews */}
      <div className="grid gap-6 md:grid-cols-2">
        {/* Left Side: Icon Sizes List */}
        <div className="space-y-3">
          <Label className="text-sm font-medium">Generated Favicon Set</Label>
          <div className="space-y-3">
            {icons.map((icon) => (
              <div
                key={icon.size}
                className="flex items-center justify-between rounded-xl border border-border bg-card p-3.5"
              >
                <div className="flex items-center gap-3">
                  <div className="flex size-12 items-center justify-center rounded-lg border border-border bg-muted/40 p-1">
                    {icon.url && (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={icon.url} alt={icon.label} className="max-h-full max-w-full object-contain" />
                    )}
                  </div>
                  <div>
                    <h4 className="font-medium text-xs">{icon.label}</h4>
                    <p className="text-xs font-mono text-muted-foreground">
                      {icon.name} • {icon.blob ? formatBytes(icon.blob.size) : ""}
                    </p>
                  </div>
                </div>

                {icon.blob && (
                  <Button
                    size="sm"
                    variant="outline"
                    className="h-8 text-xs"
                    onClick={() => downloadBlob(icon.blob!, icon.name)}
                  >
                    <Download className="size-3.5 mr-1" /> Download
                  </Button>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Right Side: Context Previews & HTML Markup */}
        <div className="space-y-5">
          {/* Simulated Browser Tab */}
          <div className="space-y-2">
            <Label className="text-xs font-medium flex items-center gap-1.5">
              <Globe className="size-3.5 text-primary" /> Browser Tab Simulation
            </Label>
            <div className="rounded-xl border border-border bg-neutral-900 p-3 text-white flex items-center gap-3">
              <div className="flex items-center gap-2 rounded-lg bg-neutral-800 px-3 py-1.5 text-xs text-neutral-300">
                {icons[1]?.url && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={icons[1].url} alt="Favicon" className="size-4" />
                )}
                <span className="truncate max-w-[140px]">My Awesome Site</span>
              </div>
              <span className="text-xs text-neutral-500 font-mono">https://my-app.com</span>
            </div>
          </div>

          {/* Simulated Mobile Shortcut */}
          <div className="space-y-2">
            <Label className="text-xs font-medium flex items-center gap-1.5">
              <Smartphone className="size-3.5 text-primary" /> Apple Home Screen Preview
            </Label>
            <div className="rounded-xl border border-border bg-gradient-to-br from-indigo-900 via-purple-900 to-slate-900 p-4 flex items-center gap-4">
              <div className="size-14 rounded-2xl bg-white/10 p-1 shadow-lg backdrop-blur flex items-center justify-center">
                {icons[3]?.url && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={icons[3].url} alt="Apple Icon" className="size-12 rounded-xl object-contain" />
                )}
              </div>
              <div className="text-white">
                <p className="font-semibold text-xs">My App</p>
                <p className="text-[10px] text-white/70">180×180 Apple Touch Icon</p>
              </div>
            </div>
          </div>

          {/* Copyable HTML Head Code */}
          <div className="space-y-2">
            <div className="flex justify-between items-center text-xs">
              <span className="font-medium flex items-center gap-1">
                <Code className="size-3.5" /> HTML &lt;head&gt; Markup
              </span>
              <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={copyHtmlMarkup}>
                {copiedHtml ? <Check className="size-3 mr-1 text-emerald-500" /> : <Copy className="size-3 mr-1" />}
                Copy HTML
              </Button>
            </div>
            <Textarea value={htmlHeadMarkup} readOnly className="font-mono text-xs h-28 resize-none bg-muted/20" />
          </div>
        </div>
      </div>
    </div>
  )
}
